export const SAMPLE_EVENTS = [
  {
    title: "React Summit 2025: Building the Future of Web",
    description: "Join us for the most anticipated React conference of the year! Learn about the latest features in React 19, Server Components, and cutting-edge performance optimization techniques from industry leaders.",
    overview: "A full-day conference featuring talks from React core team members, workshops on advanced patterns, and networking opportunities with top developers from around the world.",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&q=80",
    venue: "Tech Convention Center",
    location: "San Francisco, CA",
    date: "2025-06-15",
    time: "09:00",
    mode: "hybrid",
    audience: "Frontend developers, React enthusiasts, Tech leads",
    agenda: [
      "09:00 - Registration and Welcome Coffee",
      "10:00 - Keynote: The Future of React by Dan Abramov",
      "11:30 - Workshop: Server Components Deep Dive",
      "13:00 - Lunch Break and Networking",
      "14:00 - Performance Optimization in React 19",
      "15:30 - Panel Discussion: State Management in 2025",
      "17:00 - Closing Remarks and Afterparty"
    ],
    organizer: "React Community Foundation",
    tags: ["React", "JavaScript", "Frontend", "Web Development", "Conference"]
  },
  {
    title: "AI & Machine Learning Workshop for Beginners",
    description: "Kickstart your journey into artificial intelligence and machine learning. This hands-on workshop covers Python basics, data preprocessing, and building your first neural network.",
    overview: "An interactive beginner-friendly workshop designed to demystify AI and ML concepts through practical coding exercises and real-world examples.",
    image: "https://images.unsplash.com/photo-1677442136019-21780ecad995?w=1200&q=80",
    venue: "Innovation Hub",
    location: "Austin, TX",
    date: "2025-05-20",
    time: "10:00",
    mode: "offline",
    audience: "Beginners, Students, Career switchers, Developers",
    agenda: [
      "10:00 - Introduction to AI and ML Fundamentals",
      "11:00 - Python for Data Science Crash Course",
      "12:30 - Lunch Break",
      "13:30 - Hands-on: Data Preprocessing and Visualization",
      "15:00 - Building Your First Neural Network",
      "16:30 - Q&A and Next Steps in Your ML Journey"
    ],
    organizer: "AI Education Initiative",
    tags: ["AI", "Machine Learning", "Python", "Workshop", "Beginners"]
  },
  {
    title: "Cybersecurity Summit: Protecting the Digital Future",
    description: "A comprehensive conference addressing the latest cybersecurity threats, defensive strategies, and compliance frameworks. Learn from certified experts about zero-trust architecture, cloud security, and incident response.",
    overview: "Two-day summit featuring keynotes from cybersecurity leaders, hands-on labs, and certification preparation sessions for security professionals at all levels.",
    image: "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=1200&q=80",
    venue: "Cyber Defense Academy",
    location: "Washington, DC",
    date: "2025-07-10",
    time: "08:30",
    mode: "offline",
    audience: "Security professionals, IT administrators, CISOs, Compliance officers",
    agenda: [
      "08:30 - Registration and Breakfast",
      "09:30 - Keynote: The Evolving Threat Landscape",
      "11:00 - Zero-Trust Architecture Implementation",
      "12:30 - Networking Lunch",
      "14:00 - Cloud Security Best Practices",
      "15:30 - Incident Response Workshop",
      "17:00 - Day 1 Wrap-up"
    ],
    organizer: "National Cybersecurity Alliance",
    tags: ["Cybersecurity", "InfoSec", "Cloud Security", "Enterprise", "Conference"]
  },
  {
    title: "DevOps Days: CI/CD and Infrastructure as Code",
    description: "Master modern DevOps practices with this intensive hands-on event. Explore Docker, Kubernetes, Terraform, GitHub Actions, and learn how to build robust CI/CD pipelines.",
    overview: "A practical workshop focusing on containerization, orchestration, infrastructure automation, and implementing DevOps culture in organizations.",
    image: "https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=1200&q=80",
    venue: "Cloud Campus",
    location: "Seattle, WA",
    date: "2025-06-05",
    time: "09:30",
    mode: "hybrid",
    audience: "DevOps engineers, System administrators, Backend developers",
    agenda: [
      "09:30 - Welcome and DevOps Culture Overview",
      "10:30 - Containerization with Docker",
      "12:00 - Lunch Break",
      "13:00 - Kubernetes Orchestration Hands-on",
      "15:00 - Infrastructure as Code with Terraform",
      "16:30 - Building CI/CD Pipelines with GitHub Actions",
      "18:00 - Networking Session"
    ],
    organizer: "DevOps Institute",
    tags: ["DevOps", "Docker", "Kubernetes", "CI/CD", "Cloud", "Workshop"]
  },
  {
    title: "Mobile App Development Bootcamp: Flutter & React Native",
    description: "Build cross-platform mobile applications from scratch. Compare Flutter and React Native frameworks, understand their strengths, and create production-ready apps.",
    overview: "Three-day intensive bootcamp covering mobile development fundamentals, UI/UX design principles, state management, and deployment to app stores.",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=1200&q=80",
    venue: "Mobile Dev Studio",
    location: "New York, NY",
    date: "2025-08-12",
    time: "10:00",
    mode: "offline",
    audience: "Developers, Mobile enthusiasts, Startups, Students",
    agenda: [
      "10:00 - Mobile Development Landscape Overview",
      "11:00 - Flutter Fundamentals and Widget System",
      "12:30 - Lunch Break",
      "13:30 - React Native Components and Navigation",
      "15:00 - State Management: Provider vs Redux",
      "16:30 - Hands-on: Building a Todo App",
      "18:00 - Day 1 Summary"
    ],
    organizer: "Mobile Developers Community",
    tags: ["Mobile", "Flutter", "React Native", "iOS", "Android", "Bootcamp"]
  },
  {
    title: "Web3 and Blockchain Developer Conference",
    description: "Dive into the world of decentralized applications, smart contracts, and blockchain technology. Learn Solidity, explore DeFi protocols, and understand Web3 architecture.",
    overview: "Conference featuring blockchain experts, smart contract auditors, and successful Web3 founders sharing insights on building decentralized applications.",
    image: "https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=1200&q=80",
    venue: "Blockchain Hub",
    location: "Miami, FL",
    date: "2025-09-22",
    time: "09:00",
    mode: "hybrid",
    audience: "Blockchain developers, Crypto enthusiasts, Tech investors",
    agenda: [
      "09:00 - Registration and Welcome",
      "10:00 - Keynote: The State of Web3 in 2025",
      "11:30 - Smart Contract Development with Solidity",
      "13:00 - Lunch and NFT Gallery Exhibition",
      "14:30 - DeFi Protocols and Security Best Practices",
      "16:00 - Building dApps with Ethers.js and Web3.js",
      "17:30 - Panel: The Future of Decentralized Finance"
    ],
    organizer: "Web3 Builders Collective",
    tags: ["Blockchain", "Web3", "Solidity", "DeFi", "Cryptocurrency", "Smart Contracts"]
  },
  {
    title: "UX/UI Design Thinking Workshop",
    description: "Master user-centered design principles and learn to create intuitive, beautiful interfaces. This workshop covers design systems, prototyping tools, and user research methodologies.",
    overview: "An immersive design workshop combining theory and practice, featuring case studies from leading tech companies and hands-on design challenges.",
    image: "https://images.unsplash.com/photo-1561070791-2526d30994b5?w=1200&q=80",
    venue: "Design Studio Loft",
    location: "Los Angeles, CA",
    date: "2025-05-28",
    time: "10:00",
    mode: "offline",
    audience: "UX designers, UI designers, Product managers, Developers",
    agenda: [
      "10:00 - Design Thinking Fundamentals",
      "11:30 - User Research and Persona Development",
      "13:00 - Lunch Break",
      "14:00 - Prototyping with Figma and Adobe XD",
      "15:30 - Design Systems and Component Libraries",
      "17:00 - Hands-on Challenge: Redesign a Mobile App",
      "18:00 - Feedback Session and Networking"
    ],
    organizer: "Design Matters Collective",
    tags: ["UX", "UI", "Design", "Figma", "User Research", "Workshop"]
  },
  {
    title: "Python for Data Science and Analytics",
    description: "Transform raw data into actionable insights using Python's powerful data science ecosystem. Learn pandas, NumPy, matplotlib, and scikit-learn through real-world datasets.",
    overview: "Comprehensive workshop covering the complete data science workflow from data collection and cleaning to visualization and machine learning model deployment.",
    image: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=1200&q=80",
    venue: "Data Science Lab",
    location: "Boston, MA",
    date: "2025-07-18",
    time: "09:00",
    mode: "online",
    audience: "Data analysts, Data scientists, Researchers, Python developers",
    agenda: [
      "09:00 - Python Data Science Ecosystem Overview",
      "10:30 - Data Manipulation with pandas",
      "12:00 - Break",
      "12:30 - Data Visualization with matplotlib and seaborn",
      "14:00 - Statistical Analysis and Hypothesis Testing",
      "15:30 - Introduction to Machine Learning with scikit-learn",
      "17:00 - Q&A and Resources for Further Learning"
    ],
    organizer: "Python Data Community",
    tags: ["Python", "Data Science", "Analytics", "pandas", "Machine Learning", "Online"]
  },
  {
    title: "Cloud Architecture Masterclass: AWS, Azure, and GCP",
    description: "Compare and contrast the three major cloud providers. Learn to design scalable, resilient cloud architectures and understand when to use each platform's unique services.",
    overview: "Expert-led masterclass covering cloud architecture patterns, cost optimization, multi-cloud strategies, and certification preparation tips.",
    image: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1200&q=80",
    venue: "Virtual Cloud Campus",
    location: "Online",
    date: "2025-06-30",
    time: "11:00",
    mode: "online",
    audience: "Cloud architects, Solutions engineers, DevOps professionals",
    agenda: [
      "11:00 - Cloud Computing Fundamentals Review",
      "12:00 - AWS Core Services and Architecture Patterns",
      "13:30 - Break",
      "14:00 - Azure Services and Enterprise Integration",
      "15:30 - Google Cloud Platform and Big Data Solutions",
      "17:00 - Multi-cloud Strategies and Cost Optimization",
      "18:30 - Certification Paths and Q&A"
    ],
    organizer: "Cloud Architects Guild",
    tags: ["Cloud", "AWS", "Azure", "GCP", "Architecture", "Online", "Masterclass"]
  },
  {
    title: "Startup Tech Stack: From MVP to Scale",
    description: "Learn how to choose the right technology stack for your startup. This event covers rapid prototyping, technical debt management, and scaling strategies used by successful startups.",
    overview: "Panel discussions and workshops featuring CTOs and technical co-founders from unicorn startups sharing their technology decisions and lessons learned.",
    image: "https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=1200&q=80",
    venue: "Startup Incubator Hub",
    location: "San Jose, CA",
    date: "2025-08-05",
    time: "14:00",
    mode: "offline",
    audience: "Startup founders, CTOs, Technical co-founders, Entrepreneurs",
    agenda: [
      "14:00 - Welcome and Networking",
      "14:30 - Choosing Your MVP Tech Stack",
      "15:30 - Panel: Scaling from 0 to 1 Million Users",
      "16:45 - Break and Startup Showcase",
      "17:15 - Managing Technical Debt in Fast-Growing Startups",
      "18:15 - Workshop: Build and Deploy an MVP in 60 Minutes",
      "19:30 - Networking Reception"
    ],
    organizer: "Startup Tech Forum",
    tags: ["Startup", "Entrepreneurship", "Tech Stack", "MVP", "Scaling", "CTO"]
  },
  {
    title: "Game Development with Unity and Unreal Engine",
    description: "Enter the exciting world of game development. Learn 3D modeling basics, game physics, character animation, and publish your first game to multiple platforms.",
    overview: "Hands-on workshop comparing Unity and Unreal Engine, covering game design principles, C# and Blueprint programming, and the complete game development lifecycle.",
    image: "https://images.unsplash.com/photo-1538481199705-c710c4e965fc?w=1200&q=80",
    venue: "Game Dev Studio",
    location: "Austin, TX",
    date: "2025-09-15",
    time: "10:00",
    mode: "offline",
    audience: "Game developers, 3D artists, Indie developers, Students",
    agenda: [
      "10:00 - Game Development Fundamentals",
      "11:00 - Unity Basics and C# Scripting",
      "12:30 - Lunch Break",
      "13:30 - Unreal Engine and Blueprint Visual Scripting",
      "15:00 - Game Physics and Collision Detection",
      "16:30 - Character Animation and AI",
      "18:00 - Publishing Your Game: Platforms and Distribution"
    ],
    organizer: "Indie Game Developers Association",
    tags: ["Game Development", "Unity", "Unreal Engine", "C#", "3D", "Workshop"]
  },
  {
    title: "API Design and Microservices Architecture",
    description: "Master RESTful API design, GraphQL, and microservices patterns. Learn to build scalable, maintainable backend systems with proper documentation and testing.",
    overview: "Technical workshop covering API versioning, authentication strategies, service mesh architecture, and transitioning from monoliths to microservices.",
    image: "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?w=1200&q=80",
    venue: "Backend Engineers Hall",
    location: "Chicago, IL",
    date: "2025-07-25",
    time: "09:00",
    mode: "hybrid",
    audience: "Backend developers, API architects, Software engineers",
    agenda: [
      "09:00 - RESTful API Design Best Practices",
      "10:30 - GraphQL vs REST: When to Use Each",
      "12:00 - Lunch Break",
      "13:00 - Microservices Architecture Patterns",
      "14:30 - Service Discovery and API Gateway",
      "16:00 - API Security and Authentication",
      "17:30 - Testing and Documentation with Swagger/OpenAPI"
    ],
    organizer: "Backend Developers Network",
    tags: ["API", "Microservices", "Backend", "REST", "GraphQL", "Architecture"]
  }
];
